apiVersion: apps/v1
kind: Deployment
metadata:
  name: msg-queue-demo-deployment
spec:
  selector:
    matchLabels:
      app: msg-queue-demo
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: msg-queue-demo
    spec:
      containers:
      - name: msg-queue-demo
        image: registry.digitalocean.com/do-registry-1/msg-queue-demo:latest
        env:
        - name: KAFKA_BROKER
          value: "one-node-cluster-0.one-node-cluster.simple-msg-queue.svc.cluster.local:9092" 
        - name: KAFKA_TOPIC
          value: "test-msg"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: msg-queue-demo
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: msg-queue-demo